simplify types
JuliaMolSim/AtomsBase.jl pull request #23
Opened 2021-11-10 21:34 UTC by rkurchin

Starting to work on this. Will try to commit-by-commit remove more things (and only ever committing a working state) so if we decide we want to go only part of the way, it's easy to just revert. This present commit removes only the `AbstractElement` type, which, now that I've done it, seems like unambiguously a good idea and I don't think it was adding much of anything.

2021-11-10 22:20 UTC, rkurchin commented
Okay, there we have it! Personally, I feel quite good things up through fede982, but I'm on the fence about also removing `AbstractSystem`...I can't decide if what we gain in flexibility offsets what we would lose in being able to dispatch things with some guarantees about things like dimensionality, what sorts of particles make up the system, etc., the way we can with an `AbstractSystem` that would have those things as type parameters. Eager to discuss.

I've also made some notes to myself about other potential small tweaks, the applicability of some of which will depend on how many commits in this we keep, so I'll do them after we decide rather than cluttering up the history here.

2021-11-15 19:27 UTC, jgreener64 approved these changes
Looks good to me, readme and tests are nice too.

2021-11-16 19:24 UTC, Gregstrq requested changes
We need to add indexing versions of `position` and `species` for the concrete implementations.

2021-11-16 19:24 UTC, Gregstrq commented on README.md
> +The only required properties to be specified of the system is the species of each component of the system and the positions and velocities associated with each component. These are accessed through t
Functions `species`, `position` and `velocity` are also supposed to have indexing version.
Please, emphasize it in Readme.

2021-11-16 19:26 UTC, rkurchin commented on README.md
> +The only required properties to be specified of the system is the species of each component of the system and the positions and velocities associated with each component. These are accessed through t
they're in another PR, #8, which still has some kinks to be worked out IIRC

2021-11-16 19:26 UTC, Gregstrq commented on README.md
> +The only required properties to be specified of the system is the species of each component of the system and the positions and velocities associated with each component. These are accessed through t
We should also point out in line 55 of Readme that two proposed chainings are different implementations of the indexing versions of `something` functions.

2021-11-16 19:26 UTC, rkurchin commented on README.md
> +The only required properties to be specified of the system is the species of each component of the system and the positions and velocities associated with each component. These are accessed through t
If we want to just decide that we're only going to support linear indexing for now, though, I can add that in and maybe just close the other one and open an issue instead

2021-11-16 20:53 UTC, rkurchin commented on README.md
> +The only required properties to be specified of the system is the species of each component of the system and the positions and velocities associated with each component. These are accessed through t
Okay, so do we want to just do linear indexing for now?

2021-11-17 08:40 UTC, mfherbst commented on README.md
> +The only required properties to be specified of the system is the species of each component of the system and the positions and velocities associated with each component. These are accessed through t
I think just linear indexing for now is fine.

2021-11-17 09:08 UTC, mfherbst reviewed
A few nits, but generally LGTM.

2021-11-17 14:34 UTC, rkurchin commented on src/interface.jl
>  Base.length(::AbstractSystem) = error("Implement me")
I can see it both ways. On the one hand, it's redundant to throw an error "manually" here, but on the other, having all the required functions in the `interface.jl` file does make it a useful reference for someone who wants to sit down and implement the interface...

2021-11-17 17:02 UTC, jgreener64 commented on src/interface.jl
>  Base.length(::AbstractSystem) = error("Implement me")
I would lean towards not putting the errors here, and perhaps adding a comment if we want the information to be in that file. See the first section of https://www.oxinabox.net/2020/04/19/Julia-Antipatterns.html for some discussion.

2021-11-17 17:05 UTC, mfherbst commented on src/interface.jl
>  Base.length(::AbstractSystem) = error("Implement me")
I agree with @jgreener64 (and oxinabox) on that point very much.

2021-11-17 17:07 UTC, mfherbst approved these changes
lgtm

2021-11-17 17:51 UTC, cortner reviewed
looks good I think, just left a few fairly trivial comments.

2021-11-17 17:51 UTC, cortner commented on src/implementation_aos.jl
> +    box::SVector{D,<:SVector{D,L}}
"morally" it seems to me that `box` and `boundary_conditions` should be tuples of ... rather than SVectors. But I don't have too strong a view on that.

2021-11-17 17:51 UTC, cortner commented on src/implementation_aos.jl
> +    box::Vector{<:AbstractVector{L}},
why type this? the box could be provided as a Vector, AbstractVector, Tuple, .... same with bc and particles below. This is a convenience constructor no? I would then just make it convenient to construct the thing and enforce such strict typing.

2021-11-17 17:51 UTC, cortner commented on src/atoms.jl
> +const AbstractAtomicSystem{D} = AbstractSystem{D,Element}
I don't have time to look for the definition of AbstractSystem, so I'll add this comment here: I can sort of see why one might want to make the dimension a type parameter, though I'm not entirely sure where this is needed? 

But does the element type really have to be a type parameter in the abstract type? What is the use case?

2021-11-17 17:51 UTC, cortner commented on src/implementation_soa.jl
>  export FastSystem
I find the `FlexibleSystem` and `FastSystem` terms a bit odd. Isn't it a bit context specific when they are fast / slow / convenient / inconvenient? Why not simply call them `SystemSOA` and `SystemAOS` then it is clear what they are. There could be a convenience constructor that can construct either, depending on a flag, with default probable being the AOS but I'm not sure about it.

2021-11-17 17:51 UTC, cortner commented on src/interface.jl
> +velocity(p)::Union{Unitful.Velocity,Missing} = missing
could there be also a `momentum` function that call `velocity` and `mass` (and simply fails when there is no mass?)

2021-11-17 17:51 UTC, cortner commented on src/interface.jl
>  struct Periodic <: BoundaryCondition end  # Periodic BCs
should this have a flag `true/false`?  Since the bc is implemented as a vector (or tuple) of BCs, you probably want each element of that vector to be e.g. a `Periodic()` . But now suppose you want a system that is open in the x, y direction and periodic in the z direction (e.g. dislocations). Then you need a different type `Open()` and you have a type instability.  But with `Periodic(true), Periodic(false)` there is no problem.

2021-11-17 17:51 UTC, cortner commented on src/interface.jl
>  struct Periodic <: BoundaryCondition end  # Periodic BCs
Personally, I don't really see how one needs anything other than a boolean here? I can see many other options such as reflecting, embedding, etc but those are not really relevant for the particle system per se, but rather for fields in the background, or for the embedding one would need additional structures anyhow into which to embed the System... 

But I don't see any harm in keeping the `Periodic` type.

2021-11-17 17:51 UTC, cortner commented on src/interface.jl
> +abstract type AbstractSystem{D,S} end
ah - there it is now. So if I want a particle system that has multiple element types then I can't have that? I agree that in 99% of the cases I probably don't want that because it will likely give me type instabilities. Just making sure this is really important enough to sacrifice the flexibility?

2021-11-17 17:51 UTC, cortner commented on src/interface.jl
>  Base.length(::AbstractSystem) = error("Implement me")
Is this intended to be implemented now during interface development? Then I think an error message is fine because it will flag that this is supposed to be implemented but isn't. But if it is an interface function that a user should implement, then I don't think the error message should be there.

2021-11-17 17:55 UTC, rkurchin commented on src/implementation_soa.jl
>  export FastSystem
😆 hahaha that's what they were originally called and I changed them at @mfherbst's suggestion

2021-11-17 17:56 UTC, rkurchin commented on src/interface.jl
> +velocity(p)::Union{Unitful.Velocity,Missing} = missing
Certainly...do we think that needs to be at this top level though?

2021-11-17 17:58 UTC, rkurchin commented on src/interface.jl
> +abstract type AbstractSystem{D,S} end
I think the group of us has decent consensus that these belong here so I'm going to leave them in when I merge this, but I'll open an issue for further discussion of this point.

2021-11-17 18:01 UTC, cortner commented on src/implementation_soa.jl
>  export FastSystem
ah - sorry, that's what I get for not paying attention. Just don't have the time I'm afraid. I can't even quite put my finger on why I don't like those terms. I guess I prefer technically precise terms? Especially with an interface function a user will never have to worry about it until they know what they are doing and then they'll just go and read the docs?

2021-11-17 18:01 UTC, rkurchin commented on src/implementation_aos.jl
> +    box::Vector{<:AbstractVector{L}},
Yes, that would probably be better. I was having trouble figuring out how to write it in a general enough way...will file an issue for this too.

2021-11-17 18:02 UTC, cortner commented on src/interface.jl
> +velocity(p)::Union{Unitful.Velocity,Missing} = missing
it is so generic and universal that I think there is no harm introducing it? I don't have a strong view - you decide what you think is best.

2021-11-17 18:02 UTC, cortner commented on src/interface.jl
> +abstract type AbstractSystem{D,S} end
ok

2021-11-17 18:08 UTC, rkurchin commented
I'm going to merge this. I've filed several issues to discuss lingering questions: #25, #26, #27, #28

2021-11-17 18:09 UTC, cortner commented on src/implementation_aos.jl
> +    box::Vector{<:AbstractVector{L}},
The way I did it in JuLIP was to have a conversation function e.g. 
```julia
_convert_positions(X::Vector) = X 
_convert_positions(X::AbstractVector) = collect(X) 
_convert_positions(X::AbstractMatrix) = # convert into vector of SVectors 

_convert_bc(bc::NTuple{3, Bool}) = bc 
_convert_bc(bc::AbstractVector) = tuple(Bool.(bc)...)
```
and so forth. So this means that *ANY* sensible input will be automatically converted into the format needed internally.

2021-11-17 18:09 UTC, merged

2021-11-17 18:09 UTC, cortner commented on src/implementation_aos.jl
> +    box::Vector{<:AbstractVector{L}},
ok, will repost in the issue.